CREATE TABLE usuario (

	id INT(6) AUTO_INCREMENT PRIMARY KEY,
	email VARCHAR(60) NOT NULL,
	nick VARCHAR(30) NOT NULL,
	nome_usuario VARCHAR(60) NOT NULL,
	senha VARCHAR(16) NOT NULL,
	cpf VARCHAR(11) NOT NULL
);

